import { Verbo } from './verbo';

export const VERBOSLISTADOPT: Verbo[] = [
	
	{ id: 1, terminacion: 'ar', tipo: 'regulares', verbo: 'falar',idioma:'pt' },
	{ id: 2, terminacion: 'ar', tipo: 'regulares', verbo: 'cantar',idioma:'pt' },
	{ id: 3, terminacion: 'er', tipo: 'regulares', verbo: 'beber',idioma:'pt' },
	{ id: 4, terminacion: 'ir', tipo: 'regulares', verbo: 'partir',idioma:'pt' },
	{ id: 5, terminacion: 'ar', tipo: 'regulares', verbo: 'Perguntar',idioma:'pt'},
	{ id: 6, terminacion: 'ar', tipo: 'regulares', verbo: 'Montar',idioma:'pt'},
	{ id: 7, terminacion: 'ar', tipo: 'regulares', verbo: 'escovar',idioma:'pt' },
	{ id: 8, terminacion: 'ar', tipo: 'regulares', verbo: 'bordar',idioma:'pt' },
	{ id: 9, terminacion: 'ar', tipo: 'regulares', verbo: 'fechar',idioma:'pt' },
	{ id: 10, terminacion: 'ar', tipo: 'regulares', verbo: 'Dançar',idioma:'pt' },
	{ id: 11, terminacion: 'ar', tipo: 'regulares', verbo: 'Desmontar',idioma:'pt'},
	{ id: 12, terminacion: 'ar', tipo: 'regulares', verbo: 'Entrar',idioma:'pt' },
	{ id: 13, terminacion: 'ar', tipo: 'regulares', verbo: 'Escapar',idioma:'pt'},
	{ id: 14, terminacion: 'ar', tipo: 'regulares', verbo: 'Reparar',idioma:'pt' },
	{ id: 15, terminacion: 'er', tipo: 'regulares', verbo: 'Esquecer',idioma:'pt'},
	{ id: 16, terminacion: 'ar', tipo: 'regulares', verbo: 'Baixar',idioma:'pt'},
	{ id: 17, terminacion: 'ar', tipo: 'regulares', verbo: 'jantar',idioma:'pt' },
	{ id: 18, terminacion: 'ar', tipo: 'regulares', verbo: 'Ajudar',idioma:'pt' },
	{ id: 19, terminacion: 'er', tipo: 'regulares', verbo: 'Esconder',idioma:'pt'},
	{ id: 20, terminacion: 'ar', tipo: 'regulares', verbo: 'cantarolar',idioma:'pt' },
	{ id: 21, terminacion: 'ar', tipo: 'regulares', verbo: 'beijar',idioma:'pt'},
	{ id: 22, terminacion: 'ar', tipo: 'regulares', verbo: 'entrevistar',idioma:'pt' },
	{ id: 23, terminacion: 'ar', tipo: 'regulares', verbo: 'fotografar',idioma:'pt' },
	{ id: 24, terminacion: 'ar', tipo: 'regulares', verbo: 'Lembrar',idioma:'pt'},
	{ id: 25, terminacion: 'er', tipo: 'regulares', verbo: 'Responder',idioma:'pt'},
	{ id: 26, terminacion: 'er', tipo: 'regulares', verbo: 'correr',idioma:'pt'},
	{ id: 27, terminacion: 'ar', tipo: 'regulares', verbo: 'gritar',idioma:'pt'},
	{ id: 28, terminacion: 'ar', tipo: 'regulares', verbo: 'assinar',idioma:'pt'},
	{ id: 29, terminacion: 'ar', tipo: 'regulares', verbo: 'cheirar',idioma:'pt'},
	{ id: 30, terminacion: 'ar', tipo: 'regulares', verbo: 'Espirrar',idioma:'pt'},
	{ id: 31, terminacion: 'ar', tipo: 'regulares', verbo: 'ressonar',idioma:'pt'},
	{ id: 32, terminacion: 'er', tipo: 'regulares', verbo: 'varrer',idioma:'pt'},
	{ id: 33, terminacion: 'ar', tipo: 'regulares', verbo: 'Atirar',idioma:'pt'},
	{ id: 34, terminacion: 'ar', tipo: 'regulares', verbo: 'Treinar',idioma:'pt'},
	{ id: 35, terminacion: 'ar', tipo: 'regulares', verbo: 'viajar',idioma:'pt'},
	{ id: 36, terminacion: 'ar', tipo: 'regulares', verbo: 'andar',idioma:'pt'},
	{ id: 37, terminacion: 'ar', tipo: 'regulares', verbo: 'molhar',idioma:'pt'},
	{ id: 38, terminacion: 'er', tipo: 'regulares', verbo: 'bater',idioma:'pt'},
	{ id: 39, terminacion: 'ar', tipo: 'regulares', verbo: 'ganhar',idioma:'pt'},
	{ id: 40, terminacion: 'er', tipo: 'regulares', verbo: 'viver',idioma:'pt'},
	{ id: 41, terminacion: 'ir', tipo: 'regulares', verbo: 'dividir',idioma:'pt' },
	{ id: 42, terminacion: 'ir', tipo: 'regulares', verbo: 'permitir',idioma:'pt' },

];

export const VERBOSLISTADOPTGRUPO1: Verbo[] = [
	
	{ id: 1, terminacion: 'ar', tipo: 'regulares', verbo: 'cantar',idioma:'pt' },
	{ id: 2, terminacion: 'er', tipo: 'regulares', verbo: 'beber',idioma:'pt' },
	{ id: 3, terminacion: 'ir', tipo: 'regulares', verbo: 'partir',idioma:'pt' },
	{ id: 4, terminacion: 'ar', tipo: 'regulares', verbo: 'Dançar',idioma:'pt' },
	{ id: 5, terminacion: 'ar', tipo: 'regulares', verbo: 'Entrar',idioma:'pt' },
	{ id: 6, terminacion: 'ar', tipo: 'regulares', verbo: 'Escapar',idioma:'pt'},
	{ id: 7, terminacion: 'ar', tipo: 'regulares', verbo: 'Reparar',idioma:'pt' },
	{ id: 8, terminacion: 'er', tipo: 'regulares', verbo: 'Esquecer',idioma:'pt'},
	{ id: 9, terminacion: 'ar', tipo: 'regulares', verbo: 'Baixar',idioma:'pt'},
	{ id: 10, terminacion: 'ar', tipo: 'regulares', verbo: 'jantar',idioma:'pt' },
	{ id: 11, terminacion: 'ar', tipo: 'regulares', verbo: 'Ajudar',idioma:'pt' },
	{ id: 12, terminacion: 'er', tipo: 'regulares', verbo: 'Esconder',idioma:'pt'},
	{ id: 13, terminacion: 'ar', tipo: 'regulares', verbo: 'Lembrar',idioma:'pt'},
	{ id: 14, terminacion: 'er', tipo: 'regulares', verbo: 'correr',idioma:'pt'},
	{ id: 15, terminacion: 'ar', tipo: 'regulares', verbo: 'gritar',idioma:'pt'},
	{ id: 16, terminacion: 'ar', tipo: 'regulares', verbo: 'cheirar',idioma:'pt'},
	{ id: 17, terminacion: 'ar', tipo: 'regulares', verbo: 'Espirrar',idioma:'pt'},
	{ id: 18, terminacion: 'er', tipo: 'regulares', verbo: 'varrer',idioma:'pt'},
	{ id: 19, terminacion: 'ar', tipo: 'regulares', verbo: 'Atirar',idioma:'pt'},
	{ id: 20, terminacion: 'ar', tipo: 'regulares', verbo: 'Treinar',idioma:'pt'},
	{ id: 21, terminacion: 'ar', tipo: 'regulares', verbo: 'viajar',idioma:'pt'},
	{ id: 22, terminacion: 'ar', tipo: 'regulares', verbo: 'andar',idioma:'pt'},
	{ id: 23, terminacion: 'ar', tipo: 'regulares', verbo: 'molhar',idioma:'pt'},
	{ id: 24, terminacion: 'er', tipo: 'regulares', verbo: 'bater',idioma:'pt'},
	{ id: 25, terminacion: 'ar', tipo: 'regulares', verbo: 'ganhar',idioma:'pt'},
	{ id: 26, terminacion: 'er', tipo: 'regulares', verbo: 'viver',idioma:'pt'},


];

