import { Verbo } from './verbo';
 
export const VERBOSLISTADO: Verbo[] = [
	
	{ id: 1, terminacion: 'ar', tipo: 'regulares', verbo: 'cantar',idioma:'es'},
	{ id: 2, terminacion: 'ar', tipo: 'regulares', verbo: 'hablar',idioma:'es' },
	{ id: 3, terminacion: 'er', tipo: 'regulares', verbo: 'beber' ,idioma:'es'},
	{ id: 4, terminacion: 'ir', tipo: 'regulares', verbo: 'dividir' ,idioma:'es'},
	{ id: 5, terminacion: 'ar', tipo: 'regulares', verbo: 'Preguntar' ,idioma:'es'},
	{ id: 6, terminacion: 'ar', tipo: 'regulares', verbo: 'Armar',idioma:'es'},
	{ id: 7, terminacion: 'ar', tipo: 'regulares', verbo: 'cepillar',idioma:'es'},
	{ id: 8, terminacion: 'ar', tipo: 'regulares', verbo: 'Entregar',idioma:'es'},
	{ id: 9, terminacion: 'ar', tipo: 'regulares', verbo: 'Bailar',idioma:'es'},
	{ id: 10, terminacion: 'ar', tipo: 'regulares', verbo: 'Desarmar',idioma:'es'},
	{ id: 11, terminacion: 'ar', tipo: 'regulares', verbo: 'bordar',idioma:'es'},
	{ id: 12, terminacion: 'ar', tipo: 'regulares', verbo: 'Entrar',idioma:'es'},
	{ id: 13, terminacion: 'ar', tipo: 'regulares', verbo: 'borrar',idioma:'es'},
	{ id: 14, terminacion: 'ar', tipo: 'regulares', verbo: 'Escapar',idioma:'es'},
	{ id: 15, terminacion: 'ar', tipo: 'regulares', verbo: 'Olvidar',idioma:'es'},
	{ id: 16, terminacion: 'ar', tipo: 'regulares', verbo: 'Bajar',idioma:'es'},
	{ id: 17, terminacion: 'ar', tipo: 'regulares', verbo: 'cenar',idioma:'es'},
	{ id: 18, terminacion: 'ar', tipo: 'regulares', verbo: 'Ayudar',idioma:'es'},
	{ id: 19, terminacion: 'er', tipo: 'regulares', verbo: 'Esconder',idioma:'es' },
	{ id: 20, terminacion: 'ar', tipo: 'regulares', verbo: 'tararear',idioma:'es' },
	{ id: 21, terminacion: 'ar', tipo: 'regulares', verbo: 'cazar',idioma:'es' },
	{ id: 22, terminacion: 'ar', tipo: 'regulares', verbo: 'Entrevistar',idioma:'es'},
	{ id: 23, terminacion: 'ar', tipo: 'regulares', verbo: 'besar',idioma:'es' },
	{ id: 24, terminacion: 'ar', tipo: 'regulares', verbo: 'mirar',idioma:'es'},
	{ id: 25, terminacion: 'ar', tipo: 'regulares', verbo: 'desayunar',idioma:'es'},
	{ id: 26, terminacion: 'er', tipo: 'regulares', verbo: 'Responder',idioma:'es'},
	{ id: 27, terminacion: 'er', tipo: 'regulares', verbo: 'correr',idioma:'es'},
	{ id: 28, terminacion: 'ar', tipo: 'regulares', verbo: 'gritar',idioma:'es'},
	{ id: 29, terminacion: 'ar', tipo: 'regulares', verbo: 'firmar',idioma:'es'},
	{ id: 30, terminacion: 'ar', tipo: 'regulares', verbo: 'Estornudar',idioma:'es'},
	{ id: 31, terminacion: 'er', tipo: 'regulares', verbo: 'barrer',idioma:'es'},
	{ id: 32, terminacion: 'ar', tipo: 'regulares', verbo: 'Arrojar',idioma:'es'},
	{ id: 33, terminacion: 'ar', tipo: 'regulares', verbo: 'Entrenar',idioma:'es'},
	{ id: 34, terminacion: 'ar', tipo: 'regulares', verbo: 'viajar',idioma:'es'},
	{ id: 35, terminacion: 'ar', tipo: 'regulares', verbo: 'caminar',idioma:'es'},
	{ id: 36, terminacion: 'ar', tipo: 'regulares', verbo: 'mojar',idioma:'es'},
	{ id: 37, terminacion: 'ir', tipo: 'regulares', verbo: 'batir',idioma:'es'},
	{ id: 38, terminacion: 'ar', tipo: 'regulares', verbo: 'ganar',idioma:'es'},
	{ id: 39, terminacion: 'ar', tipo: 'regulares', verbo: 'nadar',idioma:'es'},
	{ id: 40, terminacion: 'ir', tipo: 'regulares', verbo: 'vivir',idioma:'es'},
	{ id: 41, terminacion: 'ir', tipo: 'regulares', verbo: 'permitir',idioma:'es'},
	{ id: 42, terminacion: 'ir', tipo: 'regulares', verbo: 'prohibir',idioma:'es'},
	{ id: 43, terminacion: 'ir', tipo: 'regulares', verbo: 'asitir',idioma:'es'},
	{ id: 44, terminacion: 'ir', tipo: 'regulares', verbo: 'añadir',idioma:'es'},
	{ id: 45, terminacion: 'ir', tipo: 'regulares', verbo: 'pulir',idioma:'es'},
	{ id: 46, terminacion: 'er', tipo: 'regulares', verbo: 'prometer',idioma:'es'},
	{ id: 47, terminacion: 'er', tipo: 'regulares', verbo: 'coser',idioma:'es'},

];

export const VERBOSLISTADOGRUPO1: Verbo[] = [
	
	{ id: 1, terminacion: 'ar', tipo: 'regulares', verbo: 'cantar',idioma:'es'},
	{ id: 2, terminacion: 'er', tipo: 'regulares', verbo: 'beber' ,idioma:'es'},
	{ id: 3, terminacion: 'ar', tipo: 'regulares', verbo: 'Bailar',idioma:'es'},
	{ id: 4, terminacion: 'ar', tipo: 'regulares', verbo: 'Entrar',idioma:'es'},
	{ id: 5, terminacion: 'ar', tipo: 'regulares', verbo: 'Escapar',idioma:'es'},
	{ id: 6, terminacion: 'ar', tipo: 'regulares', verbo: 'Olvidar',idioma:'es'},
	{ id: 7, terminacion: 'ar', tipo: 'regulares', verbo: 'Bajar',idioma:'es'},
	{ id: 8, terminacion: 'ar', tipo: 'regulares', verbo: 'Ayudar',idioma:'es'},
	{ id: 9, terminacion: 'ar', tipo: 'regulares', verbo: 'cazar',idioma:'es' },
	{ id: 10, terminacion: 'er', tipo: 'regulares', verbo: 'correr',idioma:'es'},
	{ id: 11, terminacion: 'ar', tipo: 'regulares', verbo: 'gritar',idioma:'es'},
	{ id: 12, terminacion: 'ar', tipo: 'regulares', verbo: 'Estornudar',idioma:'es'},
	{ id: 13, terminacion: 'er', tipo: 'regulares', verbo: 'barrer',idioma:'es'},
	{ id: 14, terminacion: 'ar', tipo: 'regulares', verbo: 'Arrojar',idioma:'es'},
	{ id: 15, terminacion: 'ar', tipo: 'regulares', verbo: 'Entrenar',idioma:'es'},
	{ id: 16, terminacion: 'ar', tipo: 'regulares', verbo: 'viajar',idioma:'es'},
	{ id: 17, terminacion: 'ar', tipo: 'regulares', verbo: 'caminar',idioma:'es'},
	{ id: 18, terminacion: 'ar', tipo: 'regulares', verbo: 'mojar',idioma:'es'},
	{ id: 19, terminacion: 'ar', tipo: 'regulares', verbo: 'nadar',idioma:'es'},
	{ id: 20, terminacion: 'ar', tipo: 'regulares', verbo: 'ganar',idioma:'es'},
	{ id: 21, terminacion: 'ir', tipo: 'regulares', verbo: 'vivir',idioma:'es'},

];

